api:
  dashboard: true

# log:
#   level: DEBUG
  
# Set Access logs timezone
accessLog:
  fields:
    names:
      StartUTC: drop

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

entryPoints:
  insecure:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: secure
          scheme: https
  secure:
    address: ":443"
    http:
      tls:
        certResolver: le
      middlewares:
        - google-oauth@file


# Allow self-signed certificates for https backends (nextcloud for example)
serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  le:
    acme:
      storage: /config/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: insecure
